d07/testCookie/App/views.py
from flask import Blueprint, url_for, render_template, request, Response, redirect, session

blue = Blueprint('first_blue', __name__)

@blue.route('/')
def index():
    return "Hello Flask"

@blue.route('/home/')
def home():
    # username = request.cookies.get("user")
    username = session.get('user')
    return render_template('home.html', username=username)

@blue.route('/login/', methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template('login.html')
    elif request.method == "POST":
        username = request.form.get("username")
        resp = Response(response="Login Success: %s" % username)
        # resp.set_cookie('user', username)
        session['user'] = username
        return resp
        

@blue.route('/logout/')
def logout():
    resp = redirect(url_for('first_blue.home'))
    resp.delete_cookie('user')
    return resp 

d07/testCookie/templates/home.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Home</title>
	</head>

	<body>

		<h2>Hello: {{ username }}</h2>
		<a href="{{ url_for('first_blue.login') }}"> Login </a>
		<br>
		<a href="{{ url_for('first_blue.logout') }}"> Logout </a>
	</body>
</html>

d07/testCookie/templates/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Login</title>
	</head>

	<body>
		<form action="{{ url_for('first_blue.login') }}" method="post">
			<span> Username: </span> <input type="text" name="username" placeholder="input your username">
			<br>
			<input type="submit">
	</body>
</html>